project_name: Semantic Segmentation for Aerial Imagery

data:
  dataset_name: flair
  raw_dir: ...
  flair:
    base_dir: /home/ryqc/data/flair_dataset
    train_csv: /home/ryqc/data/flair_dataset/cleaned-train01.csv
    val_csv: /home/ryqc/data/flair_dataset/cleaned-val01.csv
    test_csv: /home/ryqc/data/flair_dataset/cleaned-test01.csv
  dlr:
    train_dir: ...
    val_dir: ...
    test_dir: ...
  patch_size: 512
  overlap: 0.5
  patchify_enabled: true

training:
  batch_size: 16
  num_epochs: 50
  learning_rate: 1-e4
  random_seed: 42
  patience: 10
  num_workers: 2
  pin_memory: true

model:
  model_name: ...
  encoder_name: ...
  encode_weights: ...
  pretrained_weights: ...
  num_classes: 19
  image_net_mean: [ 0.485, 0.456, 0.406 ]
  image_net_std: [ 0.229, 0.224, 0.225 ]
  ade20k_mean: (np.array([123.675, 116.280, 103.530]) / 255).tolist()
  ade_20k_std: (np.array([58.395, 57.120, 57.375]) / 255).tolist()

paths:
  mask2former:
    base_output_dir: /home/ryqc/data/mask2former_outputs
    run_name: mask2former_kaggle
    logs_subdir: logs
    tensorboard_subdir: tensorboard
    checkpoint_subdir: checkpoints
    visualization_subdir: visualizations
    test_results_subdir: test_results

  unet:
    base_output_dir: /home/ryqc/data/unet_outputs
    run_name: unet
    logs_subdir: logs
    tensorboard_subdir: tensorboard
    checkpoint_subdir: checkpoints
    visualization_subdir: visualizations
    test_results_subdir: test_results

